---
abstract: FastCGI
author:
  - 'Christian Hansen C<chansen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::BinaryData: 0.007
  Test::Exception: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-FastCGI
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Exporter: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
